"""add medical_interactions

Revision ID: 7a03232956dc
Revises: 3b3d65ade9ff
Create Date: 2026-01-10 14:43:43.794630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a03232956dc'
down_revision: Union[str, Sequence[str], None] = '3b3d65ade9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('disclaimer_shown', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_interactions_conversation_id'), 'medical_interactions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_medical_interactions_id'), 'medical_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_medical_interactions_user_id'), 'medical_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_interactions_user_id'), table_name='medical_interactions')
    op.drop_index(op.f('ix_medical_interactions_id'), table_name='medical_interactions')
    op.drop_index(op.f('ix_medical_interactions_conversation_id'), table_name='medical_interactions')
    op.drop_table('medical_interactions')
    # ### end Alembic commands ###
