"""add medical safety fields

Revision ID: c0eefc9e3e42
Revises: 7a03232956dc
Create Date: 2026-01-10 23:31:31.381968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0eefc9e3e42'
down_revision: Union[str, Sequence[str], None] = '7a03232956dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Add columns as NULLABLE first
    op.add_column(
        'medical_interactions',
        sa.Column('risk_level', sa.String(), nullable=True)
    )
    op.add_column(
        'medical_interactions',
        sa.Column('emergency_detected', sa.Boolean(), nullable=True)
    )

    # 2️⃣ Backfill existing rows with safe defaults
    op.execute(
        "UPDATE medical_interactions SET risk_level = 'low' WHERE risk_level IS NULL"
    )
    op.execute(
        "UPDATE medical_interactions SET emergency_detected = FALSE WHERE emergency_detected IS NULL"
    )

    # 3️⃣ Enforce NOT NULL constraint
    op.alter_column(
        'medical_interactions',
        'risk_level',
        nullable=False
    )
    op.alter_column(
        'medical_interactions',
        'emergency_detected',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_interactions', 'emergency_detected')
    op.drop_column('medical_interactions', 'risk_level')
    # ### end Alembic commands ###
